### ISSUE TITLE
estimated date of publishing  wallet-connect on npm

### ISSUE THREAD

**Issue by realgisam** [solana-labs/wallet-adapter#112]
hello, i dont know if it's the right place to ask.
I would like to know when the wallet connect part will be published to npm?
https://github.com/solana-labs/wallet-adapter/tree/master/packages/wallets/walletconnect
Additionnally is the code safe to use ? Why it is not published?
Thanks

**Comment by jordansexton** [comment]
It's not published because it isn't operational yet. WalletConnect needs to support Solana before wallets on Solana can use it, and it doesn't yet. Additionally, wallets then need to integrate the version of WalletConnect that supports Solana (that doesn't exist) before they can use it.

It's being worked on, but there's no estimated date for delivery yet. I wouldn't recommend trying to use it because it won't work with wallets that currently support WalletConnect.

**Comment by realgisam** [comment]
> It's not published because it isn't operational yet. WalletConnect needs to support Solana before wallets on Solana can use it, and it doesn't yet. Additionally, wallets then need to integrate the version of WalletConnect that supports Solana (that doesn't exist) before they can use it.
> 
> It's being worked on, but there's no estimated date for delivery yet. I wouldn't recommend trying to use it because it won't work with wallets that currently support WalletConnect.

Thanks a lot for the clarification!

**Comment by jordansexton** [comment]
Closing this issue since there's a tracking PR now: https://github.com/solana-labs/wallet-adapter/pull/187
