### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by tayab2468** [solana-labs/wallet-adapter#169]
I'm getting this error when I try to create Account with System Program.

Error:
`WalletSendTransactionError: Signature verification failed`

Code:
```
const newAccount = new Keypair()
const createAccIx = SystemProgram.createAccount({
          fromPubkey: publicKey,
          lamports: await Token.getMinBalanceRentForExemptAccount(connection),
          newAccountPubkey: newAccount.publicKey,
          programId: TOKEN_PROGRAM_ID,
          space: AccountLayout.span,
})
 const createTokenAccountIx = Token.createInitAccountInstruction(
          TOKEN_PROGRAM_ID,
          PRESALE_TOKEN_PROGRAM,
          newAccount.publicKey,
          publicKey
)
const signature = await sendTransaction(
          new Transaction().add(createAccIx, createTokenAccountIx),
          connection
 )
const result = await connection.confirmTransaction(
          signature,
          'processed'
)
```

**Comment by jordansexton** [comment]
That error indicates an issue with the transaction validation, but isn't a bug in wallet-adapter.

I think the issue is that when you're creating a new system account, the new account keypair needs to sign the transaction. You're missing `newAccount` as a signer.

Try to pass it as a signer with the options here: https://github.com/solana-labs/wallet-adapter/blob/a883ebc5706f38235ee4d5838c2ddb458accdebf/packages/core/base/src/adapter.ts#L14-L16

These options are passed to `sendTransaction`:
```ts
await sendTransaction(transaction, connection, { signers: [newAccount] })
```

This will set the transaction fee payer to the wallet account, and then add the extra signer(s) your transaction expects.

**Comment by tayab2468** [comment]
Thanks
