### ISSUE TITLE
Keypair

### ISSUE THREAD

**Issue by shuffledex** [solana-labs/wallet-adapter#172]
Serum SDK has the placeOrder method. Part of the interface requires an owner attribute, it is an Account instance.
To create that Account, I need in some way the secretKey of the connected wallet. Is there a way to get it?

**Comment by Jacob-CG** [comment]
Using the wallet-adapter, you are giving the handling of secret keys to the wallet connected to your application. In order to create transactions you have to:

1. [Create the `Transaction`](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/example/components/SendTransaction.tsx#L20)
2. [Send the transaction](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/example/components/SendTransaction.tsx#L28)

For any other support needs, please visit [our discord](http://solana.com/discord) and ask in **developer-support**
