### ISSUE TITLE
Signing and transferring a transaction for a custom SPL token 

### ISSUE THREAD

**Issue by ricklancee** [solana-labs/wallet-adapter#189]
Hi i'm looking for documentation or examples on this subject and have difficulty finding anything. How to transfer a custom SPL token with the wallet adapter? 

I'm having trouble getting the singer for the Token object. Could you point me in the right direction? 

Adding any examples to the readme in the future on how to do this would help me and others tremendously.

```tsx
import { Token, TOKEN_PROGRAM_ID } from '@solana/spl-token'
import { Transaction, PublicKey } from '@solana/web3.js'

const SendTransaction: React.FC<Props> = ({ children }) => {
    const { connection } = useConnection()
    const { publicKey, sendTransaction } = useWallet()

    const onSendSPLTransaction = useCallback(
        async (toPubkey: string, amount: number) => {
            if (!toPubkey || !amount) return
            const toastId = toast.loading('Processing transaction...')

            try {
                if (!publicKey) throw new WalletNotConnectedError()
                const toPublicKey = new PublicKey(toPubkey)
                const mint = new PublicKey('Mint address')
                const payer = '????' // how to get this Signer
                const token = new Token(connection, mint, TOKEN_PROGRAM_ID, payer)
                const fromTokenAccount = await token.getOrCreateAssociatedAccountInfo(publicKey)
                const toTokenAccount = await token.getOrCreateAssociatedAccountInfo(toPublicKey)

                const transaction = new Transaction().add(
                    Token.createTransferInstruction(
                        TOKEN_PROGRAM_ID,
                        fromTokenAccount.address,
                        toTokenAccount.address,
                        publicKey,
                        [],
                        0
                    )
                )

                const signature = await sendTransaction(transaction, connection)

                const response = await connection.confirmTransaction(signature, 'processed')
                console.log('response', response)
                toast.success('Transaction sent', {
                    id: toastId,
                })
            } catch (error) {
                toast.error(`Transaction failed: ${error.message}`, {
                    id: toastId,
                })
            }
        },
        [publicKey, sendTransaction, connection]
    )

    return <>{children(onSendSPLTransaction)}</>
}
```

**Comment by jordansexton** [comment]
Ah, this isn't really an issue with wallet-adapter. It's a shortcoming of the `Token` class -- it doesn't really work with a wallet where you don't have the Keypair/Signer to pass around.

There is a TypeScript port of `@spl-token` which makes some of this easier, but it's still under review and hasn't been released on NPM yet: https://github.com/solana-labs/solana-program-library/pull/2539

I would recommend checking for the associated token account, and creating it yourself in an instruction to the transaction you sign with the wallet. These links from that open PR may help in understanding how to do this:

https://github.com/solana-labs/solana-program-library/blob/jsx/token-ts/token/ts/src/actions/getOrCreateAssociatedTokenAccount.ts

https://github.com/solana-labs/solana-program-library/blob/jsx/token-ts/token/ts/src/state/mint.ts#L114-L129

https://github.com/solana-labs/solana-program-library/blob/jsx/token-ts/token/ts/src/instructions/transfer.ts

I'm closing this since it's out of scope for this library, but I hope it helps.

**Comment by ricklancee** [comment]
Thanks so much for the answer, really helped me and i managed to get it working with some tweaking 💪💪

**Comment by block-dev1** [comment]
I am trying to burn the SPL tokens but getting a buffer error. How can I solve this issue?
Detail of this issue: 
https://stackoverflow.com/questions/72432042/how-to-create-a-transaction-to-burn-spl-tokens-in-react-app
