### ISSUE TITLE
@solana/wallet-adapter-material-ui still has reference to @material-ui/core

### ISSUE THREAD

**Issue by CalebEverett** [solana-labs/wallet-adapter#225]
**Describe the bug**
@solana/wallet-adapter-material-ui installed from package registry still has reference to @material-ui/core WalletConnectButton.tsx

**To Reproduce**
npm install @solana/wallet-adapter-material-ui
node_modules/@solana/wallet-adapter-material-ui/src/WalletConnectButton.tsx

```js
import { Button, ButtonProps } from '@material-ui/core';
...
```

**Comment by jordansexton** [comment]
Ah, I think this may be because the mui5-based version hasn't been published yet. I'll check on it, ty

**Comment by CalebEverett** [comment]
Ok, thanks - in the mean time,

```
yarn add @material-ui/core @material-ui/icons
```

gets it to run

**Comment by jordansexton** [comment]
Oh -- that's probably because those packages are peer dependencies. The version you're probably looking at:

https://github.com/solana-labs/wallet-adapter/blob/8245d65f94d7e4d0894aa1f10d74689a1394121c/packages/ui/material-ui/package.json#L23-L24

The current version in master:

https://github.com/solana-labs/wallet-adapter/blob/c8458900e26ba3574c0a2683eefbcbfb8d613ea4/packages/ui/material-ui/package.json#L23-L24

This just means they are expected to be installed by you alongside the necessary wallet-adapter packages.

We can probably change these to proper dependencies, especially when we fix the build to export ESM and CJS. @cogoo wdyt?

**Comment by CalebEverett** [comment]
Adding the @material-ui deps means the theming is different. Is there a way to install otherwise until you publish master?

**Comment by jordansexton** [comment]
Can you share a link to a repo with the issue? I want to make sure I understand what's wrong. I'll fix and publish today.

**Comment by CalebEverett** [comment]
It very well could be operator error. I couldn't figure out how to install from github, so just copied the files from master into the project and am using them instead of what was coming in from install @solana/wallet-adapter-material-ui, which then eliminates all dependencies on @material-ui. If you use @solana/wallet-adapter-material-ui currently without also having @material-ui/core and @material-ui/icons as dependencies, when you try to build the project it complains that it can't find those packages.

I think you could validate the issue by initing a project, adding @solana/wallet-adapter-material-ui and then checking node_modules to see that package.json has the @material-ui dependencies.

**Comment by jordansexton** [comment]
Okay, thanks for the explanation. I'll publish the latest MUIv5 packages and hopefully this is fixed!

**Comment by jordansexton** [comment]
Published:
@solana/wallet-adapter-material-ui@0.15.0
@solana/wallet-adapter-material-ui-starter@0.11.0

Please let me know if this fixes it!

**Comment by CalebEverett** [comment]
That did it - thanks so much!
