### ISSUE TITLE
Unable to install required dependencies for example starter project

### ISSUE THREAD

**Issue by nibbus0x** [solana-labs/wallet-adapter#233]
**Describe the bug**
Installing dependencies for `wallet-adapter/packages/starter/examples` after fresh install fails with error `No matching version found for @solana/wallet-adapter-ant-design@^0.11.0`

**To Reproduce**
1. run `git clone git@github.com:solana-labs/wallet-adapter.git`
2. cd into `wallet-adapter/packages/starter/examples`
3. run `npm install`

**Expected behavior**
All required packages should be installed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version [e.g. 2.04]

**Additional context**
When trying to install dependencies with yarn no error is even displayed. It simply does not install most of the dependencies which lead to problems when running `yarn dev`

**Comment by jordansexton** [comment]
This is because `yarn install` and `yarn build` need to be run from the project root first. See https://github.com/solana-labs/wallet-adapter#build-from-source for instructions.

After you do those steps, you can

```shell
cd packages/starter/examples
yarn dev
```

One warning -- the Material UI components in the example aren't working at the moment. There's a build issue with them, it's being sorted out.
