### ISSUE TITLE
Add wallet adapter

### ISSUE THREAD

**Issue by ludowkm** [solana-labs/wallet-adapter#234]
We would like to add our wallet adapter to have in this repository for everyone to use.
Could you tell me the steps to join here, thank you so much!

**Comment by jordansexton** [comment]
Sure, what kind of wallet is it?

**Comment by ludowkm** [comment]
Thank you so much for fast reply!
It's multi-chains mobile wallet with in-app browser.
We want to help user to browse DApps via in-app browser on Solana network then we would like to have a choice for all DApps which want to integrate us.

**Comment by jordansexton** [comment]
It sounds it might work similarly to the Slope or Phantom adapters then.

In general, the process is just to find an existing adapter you want to base it on. I recommend checking several of them out to see what kind of interfaces they support.

In a new branch, copy one of them, modify it to work with your wallet, and open a PR.

The wallet will need to be testable in order to be reviewed, and work on all Solana clusters (Mainnet Beta, Devnet, and Testnet).

**Comment by ludowkm** [comment]
Thank you @jordansexton so much for the information, we will prepare carefully to submit soon!

**Comment by jordansexton** [comment]
Sounds good! I'll close this issue for now, but I'll look forward to your PR.
