### ISSUE TITLE
Is there a way to fetch Project-Serum Provider from Wallet Adapter?

### ISSUE THREAD

**Issue by zkhalapyan** [solana-labs/wallet-adapter#270]
**Is your feature request related to a problem? Please describe.**

I am loading candy machine using anchor, which requires a [Provider](https://project-serum.github.io/anchor/ts/classes/Provider.html) object. Seems like Wallet Adapter provides connection, wallet, and signTransaction(..) separately. Is there a way to fetch [Provider](https://project-serum.github.io/anchor/ts/classes/Provider.html)? 

**Describe the solution you'd like**

Have a hook for fetching a project serum Provider: 

```JS
const { provider } = useProvider();

```

**Describe alternatives you've considered**
There is hacky ways of making a provider out of wallet, connection, etc. provided separately, but the solution is fragile.

**Comment by jordansexton** [comment]
The short answer (I think) is no, not directly. This `Provider` class is specific to Anchor. It'll be up to you to instantiate it. However, it appears that [the constructor](https://github.com/project-serum/anchor/blob/44b66c5e8428481b5885e6d65473956fbf6dd48f/ts/src/provider.ts#L25-L29) expects some arguments --

- A `connection` object, which you can get from [`useConnection`](https://github.com/solana-labs/wallet-adapter/blob/master/packages/core/react/src/useConnection.tsx) in the react package
- A `wallet` object, which you _may_ be able to get from [`useAnchorWallet`](https://github.com/solana-labs/wallet-adapter/blob/master/packages/core/react/src/useAnchorWallet.ts) since this is designed to be [compatible with what Anchor expects](https://github.com/project-serum/anchor/blob/44b66c5e8428481b5885e6d65473956fbf6dd48f/ts/src/provider.ts#L223)
- Some optional options, which you can provide

If you find this doesn't work, please let me know.

**Comment by zkhalapyan** [comment]
Thanks, let me try this out, will write up my findings.

**Comment by jordansexton** [comment]
Please do! I'm curious about it. Anchor is so great. I definitely want to make sure we play well together.

**Comment by zkhalapyan** [comment]
Yep, this works:

```JS
  const { connection } = useConnection();
  const anchorWallet = useAnchorWallet();
  const { connecting, connected, publicKey, select, connect } = useWallet();

  useEffect(() => {
    if (publicKey && anchorWallet && connection) {
      const provider = new Provider(connection, anchorWallet, {
        preflightCommitment: "processed",
      });
      // use your newly created provider...
    }
  }, [publicKey, anchorWallet, connection]);

```

**Comment by jordansexton** [comment]
Great! Thanks for sharing.

Also, I think you wouldn't need `useWallet` here since the instance returned by `useAnchorWallet` will change with the public key and may result in fewer renders.

**Comment by zkhalapyan** [comment]
Ah, that's a good idea, can use `anchorWallet.publicKey` 🙂

**Comment by jordansexton** [comment]
If you have any desire to expand on this in the FAQ, I imagine it would help a lot of people. 🙇🙇🙇

**Comment by zkhalapyan** [comment]
@jordansexton added a PR 🙂

**Comment by fonko** [comment]
man, this was the thread i have been looking for the past 2 days. God bless you both

**Comment by fonko** [comment]
man, there are so many broken links in anchor https://project-serum.github.io/anchor/ts/index.html like it wasn't already difficult to deal with blockchain stuff for a chain that doesn't use an EVM 😭
