### ISSUE TITLE
Is there a way to await for the results of setVisible(...)? 

### ISSUE THREAD

**Issue by zkhalapyan** [solana-labs/wallet-adapter#273]
**Is your feature request related to a problem? Please describe.**
In case the user is not connected, I show the modal dialog via `setVisible(true)`, and immediately after, I would like to check if `publicKey` is set and kick off the minting process. I could use this via setting a flag, and then check it via `useEffect(..)`, but ideally, there would be some callback.

**Describe the solution you'd like**

```JS
const { presentWalletLoginModal } = useWalletModal();
..
const walletLoginModalResults = await presentWalletLoginModal();
if (walletLoginModalResults.connected) {
   mint(walletLoginModalResults.publicKey, ...)
} 
```

**Describe alternatives you've considered**
I could use `select(...)` and `connect(...)` but this means I would need to rewrite the modal wallet flow, which I would rather not.

**Comment by jordansexton** [comment]
To your direct question, the answer is no. You can't rely on state changes to happen synchronously. Like you mentioned, you can use `useEffect` to react to `visible` changing though. This is really just a React thing, and the recommended pattern for doing this.

But why wouldn't you check for the public key first? Opening the modal doesn't set it. There are no "results" to speak of -- the action of showing the modal doesn't have a promise because it doesn't imply that a wallet will be selected, auto connected, etc.

The UI layer that includes the modal is it's own package, and it handles state changes the same way through the context. It's generally not a good pattern to try to await promises inside your UI.
