### ISSUE TITLE
useWallet() returns publicKey as undefined

### ISSUE THREAD

**Issue by UjjwalGupta49** [solana-labs/wallet-adapter#283]
I'm using useWallet() react hook from @solana/wallet-adapter-react, as

`const { publicKey } = useWallet();`

```
    const Connected = useCallback(async () => {
        try {
            if (!publicKey) {
                console.log('Wallet not connected');
            } else {
                console.log('Wallet connected');
                console.log(publicKey);
            }
           console.log(publicKey);
        } catch (err) {
            console.log(err);
        }
    }, [publicKey]);

    return <button onClick={Connected}>Check Connection</button>;
```

I'm using wallet-adapter-react-ui

with solana/web3.js, and Phantom wallet

**Comment by jordansexton** [comment]
Sorry, there isn't enough context here to see what the issue is.

It sounds like your issue is due to not wrapping your application with the context provider. Please check the FAQ for this.

When reporting a bug, please fill out the bug report template provided, and provide a link to a repo with a reproduction of the issue.

**Comment by UjjwalGupta49** [comment]
Thanks, @jordansexton , The issue is now resolved, I did not call the components inside the Context-

```
            <Context>
                <Content />
                <GetBalance />
            </Context>
```

**Comment by jordansexton** [comment]
Glad you figured it out!
