### ISSUE TITLE
Svelte code using out of date Wallet type

### ISSUE THREAD

**Issue by makeitTim** [solana-labs/wallet-adapter#288]
I'm trying to setup a wallet in Svelte. The base example code here seems ot be using an out of date Wallet type:
https://github.com/solana-labs/wallet-adapter/tree/master/packages/core/svelte

**Comment by makeitTim** [comment]
I see the Wallet was removed from base in this commit:
https://github.com/solana-labs/wallet-adapter/commit/37b566336af43ec059e1218ea2f1f0fe57042e24

So we're not referring to Wallets by Name or something like that? The Svelte wallet store code is still built around the Wallet type, I don't really know where to start to get it working.

**Comment by cogoo** [comment]
Hey, #278 has some related comments.

Might be worth checking out https://dev.to/0xmuse/accelerated-guide-to-fullstack-web3-with-ass-anchor-solana-and-svelte-1mg on how to connect to a wallet.

Possibly won't get round to updating the svelte core and UI packages till next week. @silvestrevivo may be able to link to another example repo that you could use in the meantime.

**Comment by silvestrevivo** [comment]
@makeitTim at this moment the Svelte core for the wallet adapter is not updated. There are some breaking changes with the last versions of the wallet packages. We are working to have an updated version that will be published very soon and will can be used for SvelteKit. 

In the meantime, you can use the example that @cogoo is mentioning if you want to work with a SPA based on the old svelte template, or otherwise in the case you want to work with SvelteKit, use this repo from me https://github.com/silvestrevivo/solana-svelte-counter . Take in consideration what this repo is not using the last versions of `@solana/wallet-adapter-base` and `@solana/wallet-adapter-wallets`.

**Comment by revick** [comment]
Eagerly awaiting the updated svelte package; Keep up the good work!

**Comment by makeitTim** [comment]
The tutorial looks interesting and informative. It doesn't use any of the wallet-adapter library at all... it's wallet connection is super simple, just:
```
const { solana } = window as any;
wallet = solana;
```
My Phantom wall Chrome Extension is expected to inject itself into window? Is that how all wallets should work?

Anyways, I cannot get this to work. If I could, would be possible to write my own svelte store code.

Any other examples would be great? This documented anywhere?

**Comment by makeitTim** [comment]
> ... or otherwise in the case you want to work with SvelteKit, use this repo from me https://github.com/silvestrevivo/solana-svelte-counter . Take in consideration what this repo is not using the last versions of `@solana/wallet-adapter-base` and `@solana/wallet-adapter-wallets`.

That looks informative but seems too out of date a few ways to run itself. Thanks I'll look. I'd love to full understand everything and implement it myself .... but it the wallet library updates that seems better.

**Comment by jordansexton** [comment]
Svelte support is going to become community maintained! Please subscribe to #298, which will be completed and merged when @cogoo and @silvestrevivo release Svelte packages.
