### ISSUE TITLE
Way for iOS app to connect to Solana wallets

### ISSUE THREAD

**Issue by akelaholmes** [solana-labs/wallet-adapter#311]
**Is your feature request related to a problem? Please describe.**
After some digging seems like connecting to a Solana wallet via an iOS app is not possible... seems like a major missing piece? 

Doesn't even have to be iOS specific, just a way to connect to a wallet that does not involve the Chrome extension, such as what they have on ETH/WalletConnect with the QR code you get from the app and you just paste into your wallet.

**Describe the solution you'd like**
A way for an iOS app to connect with one of the Solana iOS wallet apps. 

**Describe alternatives you've considered**
There are none?

**Comment by snownoop** [comment]
I am wondering the same inside my issue request.
will close it in prior of this one.

**Comment by jordansexton** [comment]
This is something wallets will need to implement support for. There isn't anything to be done yet within wallet-adapter. Once some wallets have defined a way for mobile browsers and mobile apps to communicate with them, we can define adapters or converge on a standard.

Closing for now since this isn't actionable or in scope yet, but I'll reopen when it becomes viable.
