### ISSUE TITLE
Add an onClose callback to WalletMultiButton

### ISSUE THREAD

**Issue by charly-helio** [solana-labs/wallet-adapter#359]
**Problem**
So, I want to build a webapp using the `WalletMultiButton`.
I ask for the user to pay something and we show the `WalletMultiButton` that renders on the screen the Solana's modal with the multi button. Once we are connected to a wallet with success and when multi button modal is closed, imagine that I want to show a spinner because I'm reaching other stuff  or show a message to the user or even send to a custom API that the user is connected to a wallet in a certain timestamp (or whatever action that you can image).

If I'm not wrong there is no a "callback" prop when the modal is closed. It can be done with listeners and other workaround but it's harder.

**Proposed solution**
Add an `onClose` or `onCloseModal` etc.. prop to send a callback to execute when the multi button modal to connect to a wallet is closed.

We could use it like this:

`<WalletMultiButton onClose={() => myFakeCallback} />`

And on `WalletModal.tsx` add a callback to props and trigger it at handleClose function. (https://github.com/solana-labs/wallet-adapter/blob/e89adf6cdc59ca33db0fcc3a27841a1f94a8b8ed/packages/ui/react-ui/src/WalletModal.tsx#L55)

What do you think? Is there another way to do that?

Thanks for your big effort! :)
Charly.

**Comment by jordansexton** [comment]
Hmm this is probably the wrong way to think about what the modal is doing. The modal closing doesn't mean a wallet has been selected. The simplest way to respond to a wallet being selected and connecting to it is to either enable `autoConnect` on the `WalletProvider`.

If you want to do this manually, or do something else instead of connecting when it's selected, the right paradigm in React is to use `useEffect` to respond to state changes. In this case, the `wallet` property of the context is what you'd want to respond to changes on.

If you really are looking to respond to the modal closing, this doesn't seem like something we'll implement, but you could pretty easily modify the react-ui package if you need this.
