### ISSUE TITLE
Similar to "An error was reported in next.js project #153"

### ISSUE THREAD

**Issue by josephfernandez** [solana-labs/wallet-adapter#386]
**Describe the bug**
Same issue stated in #153 

**To Reproduce**
Visit my repo at https://github.com/josephfernandez/titansea/tree/wallet.  Start app using `npm run dev` then notice localhost:3000/mint shows identical error.

**Expected behavior**
See "select wallet modal" appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 100.0.4896.75 (Official Build) (64-bit)

**Additional context**
Notice the _app.js file - it attempts to do dynamic import as suggested in #153 importing context/ClientWalletProvider.js

**Comment by jordansexton** [comment]
Please try using the provided [nextjs-starter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/nextjs-starter) project. #153 is closed because the underlying issue has been resolved. You may also want to check https://github.com/solana-labs/wallet-adapter/issues/238#issuecomment-1004557715.
