### ISSUE TITLE
Update Usage example in README

### ISSUE THREAD

**Issue by ezeev** [solana-labs/wallet-adapter#506]
The example in the README contains a call to a function that is deprecated:

![image](https://user-images.githubusercontent.com/15079807/183314575-2f991bda-c336-403c-8815-b594ae54d262.png)

**Comment by mattjohnpowell** [comment]
Looking at the code, it looks like it's based off the old Solana Web3. i.e. not just a usage example update will fix it.

**Comment by jordansexton** [comment]
This warning is because of this: https://github.com/solana-labs/solana/blob/b0c6c31b71eac944585cdede48dac63db32007f6/web3.js/src/connection.ts#L3055-L3065

However, while deprecated, this API will still be supported at least until web3.js reaches 2.0, which will most likely as a result of a total rewrite of the lib.

If anyone is interested in fixing this in the example code though, a PR is welcome!

**Comment by jordansexton** [comment]
Done in https://github.com/solana-labs/wallet-adapter/pull/522
