### ISSUE TITLE
create-react-app-starter does not work

### ISSUE THREAD

**Issue by 5elfle5** [solana-labs/wallet-adapter#510]
**Describe the bug**
I cloned your repo, went into create-react-app-starter directory, did "npm install" and "npm run start", there are 4 errors, app doesn't work

**To Reproduce**
1. Go to create-react-app-starter directory,
2. npm install
3. npm run start
4. See errors

**Expected behavior**
No errrors

**Screenshots**
<img width="753" alt="Screenshot 2022-08-11 at 15 59 34" src="https://user-images.githubusercontent.com/57477431/184138951-38f89abc-abb9-462f-a303-91f7e5ad1c8f.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Chrome

**Comment by jordansexton** [comment]
This is not a bug. It's because you didn't build the rest of the library packages. Please follow the instructions on building from source: https://github.com/solana-labs/wallet-adapter#build-from-source

In the last step, instead of `cd packages/starter/react-ui-starter`, do `cd packages/starter/create-react-app-starter`, then `yarn start`.
