### ISSUE TITLE
Example from README doesn't work

### ISSUE THREAD

**Issue by 5elfle5** [solana-labs/wallet-adapter#511]
**Describe the bug**
Example from README doesn't work

**To Reproduce**
1. npx create-react-app my-app --template typescript
2. cd my-app
3. yarn add as in README
4. add Wallet.tsx and SendOneLamportToRandomAddress.tsx with the code from example
5. change App.tsx code to "function App() {
  return (
    &lt;Wallet&gt;&lt;/Wallet&gt;
  );
}"
6. yarn start
7.  see errors 
8. try eject, and fix the webpack config
9. doesn't help

**Expected behavior**
Working example app

**Screenshots**
<img width="1412" alt="Screenshot 2022-08-11 at 16 12 31" src="https://user-images.githubusercontent.com/57477431/184141364-71ef4f5e-902d-473b-98bd-d369aa4994df.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by jordansexton** [comment]
This is not a bug. Create React App 5, because it uses Webpack 5 doesn't polyfill Node modules by default. You have to instruct it to do so.

However, we provide a Create React App starter project that you can use, which uses react-app-rewired to do this. Follow the instructions to build from source: https://github.com/solana-labs/wallet-adapter#build-from-source

In the last step, instead of `cd packages/starter/react-ui-starter`, do `cd packages/starter/create-react-app-starter`, then `yarn start`.
