### ISSUE TITLE
Flagging a wallet?

### ISSUE THREAD

**Issue by Valleriani** [solana-labs/wallet-adapter#573]
**Is your feature request related to a problem? Please describe.**
Flag Slope Wallet?

**Describe the solution you'd like**
Slope has not been really communicating with the community. (A month+ on twitter, discords pretty dead too.). The issue is people 'still' use slope so removing the wallet is probably not a good idea, but maybe explaining that users should move to another wallet until the issue is fully resolved.

They even recommend abandoning their current wallet and at least making a new wallet: https://slope-finance.medium.com/slope-wallet-sentry-vulnerability-digital-forensics-and-incident-response-report-d7a5904e5a39

It's mostly just a 'trying to save people/move your stuff to at least a new wallet' thing. The wallet was already removed from the app store. I think it might be a good idea to at least have a little flag warning and linking an article or something to it. I know we can say 'it's not our problem' but I think for Solana itself it's better to be proactive with protecting the users rather then washing our hands on the matter.

**Comment by jordansexton** [comment]
Wallet Adapter does not promote or censor wallets. It's an adapter layer for the wallets that exist, nothing more. The existence of an adapter for a wallet does not imply quality, security, testing, or approval of a wallet, nor does the inverse. Adapters are mostly added by teams that build wallets. We don't decide which ones are good or not, or even install them.

Speaking of Slope specifically, the Slope adapter has existed since before Slope had a mobile app, when there was only browser extension. To the best of my knowledge (and I was part of the security group that handled the issue) the browser extension was not affected by the issue that caused a leak of key material.

Even if it had been affected, we wouldn't pull the adapter. Wallet Adapter never has access to key material, since it's entirely downstream of wallets themselves. And it's not Wallet Adapter's purpose to tell users or devs what to do, but to make all wallets easier to use without respect to, or prohibition of, any particular wallet.
