### ISSUE TITLE
Usage example issue

### ISSUE THREAD

**Issue by ymc182** [solana-labs/wallet-adapter#62]
I have an issue when following the example, the button is created and showing phatomRPCJSON with the pubkey when its connected, but I can't use the button in Usage example and it's throwing not connected error, did I missed anything?
![image](https://user-images.githubusercontent.com/12613450/132738239-35762b71-686b-4ba7-ab7a-e64be547605c.png)

**Comment by jordansexton** [comment]
Hmm. Can you publish a repo with your example project? I can take a look at what's going on. Hard for me to tell from just the screenshot unfortunately.

**Comment by ymc182** [comment]
Thanks for the quick reply,
I have created the repo and it did reproduce the problem
https://github.com/ymc182/testSol

**Comment by jordansexton** [comment]
The issue is that your connection / wallet providers need to be the ancestor components of anything that calls useConnection / useWallet. You have them as siblings. Wrap your app with the contexts.

![Screenshot_20210909-153859](https://user-images.githubusercontent.com/1173161/132759609-187b7545-0be2-48ad-a78b-089db512a553.png)

**Comment by jordansexton** [comment]
Take a look at the example project for how this is done. You basically want those contexts at the top level of your app.

**Comment by ymc182** [comment]
Thanks very much!
