### ISSUE TITLE
Decompose React UI library into abstract components (implement function) and concrete UI (implement default styles)

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/wallet-adapter#658]
# Problem

#649 brought into focus something that's been a problem with the React UI library for a long time. Because this library is so prescriptive about style and structure, it makes basic things like styling i18n next to impossible or wildly inefficient.

For instance, this good-faith [effort to add translations](https://github.com/solana-labs/wallet-adapter/pull/650) to the library both:

1. Increased the size of the UI library, and
2. Forced everyone to download every language set, no matter which one they use.

# Proposed solution

Dismantle this library into style-and-structure agnostic pieces:

1. a set of abstract components that implement the default functionality of the controls. Use Next.js' `<Link>` or [Radix](https://www.radix-ui.com/) as inspiration.
2. a set of concrete UI controls that you can use as defaults, or supply your own.

In all cases, strings – for instance – should be taken in as props, so that everyone can use their own i18n infra.

This will be a breaking change, and will require a major version bump.

Blocks #649.

**Comment by flodef** [comment]
I would love to suggest a solution while Steve's "Proposed solution" is being build / taken care of:
1. Accept the merge of #650 for the time being.
2. Once the library is dismantled, improve the translation.

Seem to me the problem here is not well understood ==> NOBODY wants to use an app that displays exotic language he/she does not understand. It should be top priority to solve this, right now!
Steve's "Proposed solution" will taking months to implement... During this time, users are not onboarding.
Let's measure objectively the Benefits Versus Risks. I feel it's a no-brainer.
I'm open to any suggestions.

**Comment by viniblack** [comment]
I believe that making it available in other languages is essential for more people to join the network.

unfortunately it is not true that most people in the world know English

**Comment by danicuki** [comment]
Actually, 1 in 8 people in the world speak English. An i18n wallet feature can immediately make possible to onboard 8x more people to the Solana ecosystem. I believe the downside of a non-optimal architecture (that is completely usable) now is compensated by the more users using the Wallet.

**Comment by flodef** [comment]
I received a very moving message from @steveluscher yesterday.
Please guys, no more brigading (same tweet repeated)... I understand it's a way to show that's a feature we really need, but Steve got our point and is trying his best.
Let's try to be constructive and help him achieve our common goal by providing some ideas:

1. Create a fork of the wallet_adapter called wallet_adapter_intl on the Solana labs' repository (or on other repo if linked from the Solana labs' repo)  ==> English users have the current light version loading only english, Non-English users have the "heavy" version with all the languages (but those selecting it choose language over fast loading) ==> solving both problems!
2. Lazy load only one language file as the end user need one language at a time ==> solving one of the 2 problems!

Please, let me know if this can be done for the time being (while waiting for React UI library to be decomposed)

**Comment by danicuki** [comment]
From what I saw, the library size today is 172kb
Every new language added to the dictionary would required ~350 bytes
So having the top 10 spoken languages to the dictionary would add 3.5kb to the total library size.
I understand that this solution is not for all languages, and not scalable, but it could be accepted on the short term to give access to another 4 billion people, while people can work on the long term version that will be more flexible and smaller to accept any language.

The average page size for websites is ~2.2MB - adding another 4-10kb to this accounting doesn't change too much. 
We are (still) not Google, that needs to optimize every single byte for the end-user. We want billions of people using Solana. 

Let's remember [Donald Knuth words](https://wiki.c2.com/?PrematureOptimization):
"The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times; premature optimization is the root of all evil (or at least most of it) in programming"

**Comment by danicuki** [comment]
@jordansexton @steveluscher any comments on our proposals?

**Comment by danicuki** [comment]
🏓

**Comment by flodef** [comment]
Meanwhile ... on CT, @jordansexton is asking :

> One of the things Ethereum has done a great job of is cultivating open source contributions.
> What can Solana Labs and Foundation devs do to make contributing to Solana easier?
> What are we not doing well at right now? Please tell me about your experiences (positive and negative)

https://twitter.com/jordaaash/status/1608900210973106177

**Comment by jordansexton** [comment]
I think there's enough context here. Steven and I have been away for the holidays, and have multiple initiatives we're focused on. We get Github notifications just like everyone else, and we have to prioritize. Please keep the discussion additive and on topic.

Steven has already closed https://github.com/solana-labs/wallet-adapter/pull/650 and I agree with his rationale. He opened this tracking issue to describe a path forward, and stated that there isn't a timeline for this. Rather than attempt to do everything in `react-ui`, `material-ui`, and other packages, we should provide a library of components that are easier to customize at the application level.

I'm sympathetic to the fact that this doesn't point to a near-term solution, and I'm happy to promote alternative approaches without taking on the burden of maintenance for them. If you have an implementation of these components in mind that handles i18n in a particular way, please publish it, and let's link it from here for now: https://github.com/solana-labs/wallet-adapter/blob/master/PACKAGES.md#ui-components

**Comment by flodef** [comment]
Thank you so much for the great work done ! 
I'm really glad. Congrats :tada:

**Comment by steveluscher** [comment]
For sure! I'll shipit tomorrow.
