### ISSUE TITLE
Add Vue support

### ISSUE THREAD

**Issue by jordansexton** [solana-labs/wallet-adapter#67]
I'm not a user of Vue, but if anyone wants to PR `vue` and `vue-ui` packages based on the `react` and `react-ui` packages, I'd be happy to accept them.

**Comment by goldcoders** [comment]
there should be a vue and svelte version of this....

**Comment by danmt** [comment]
PRs are welcome @goldcoders

**Comment by scorpnode** [comment]
Would like a vue adapter as well please.

**Comment by jordansexton** [comment]
I don't use Vue or Svelte, but I'm happy to accept contributions to support them. I opened this issue to encourage contribution, so please open a PR if this is something you'd like to see. 🙇‍♂️

**Comment by SilverSeva** [comment]
We need that wallet-adapter-vue please

**Comment by lorisleiva** [comment]
Hi there 👋 

I've managed to use the wallet adapter using a Vue3 application.

Here's the code: https://github.com/lorisleiva/solana-vue3-counter/tree/9321e7c584906b3844d1c3eb1b69321f3ba8343d/app/src

It's a simple counter application but I've gathered most of the logic in `useWallet` and `useWorkspace` files.

I hope this helps. 🍀

**Comment by danmt** [comment]
That looks nice @lorisleiva, are you willing to put a PR for it?

**Comment by lorisleiva** [comment]
I could certainly try. 🙂 

I've got two freelance jobs on the go at the moment so I might be a bit slow though.

Is it okay for me to use TailwindCSS for the UI?

**Comment by danmt** [comment]
I'd recommend doing the adapter first and then discuss the UI part, just so the PRs are a bit easier to digest.

I don't think there's a hurry, if somebody really needs it, they can do it themselves. Thanks a lot for stepping up and offer the solution you're using.

Regarding TailwindCSS, I'm really a fan of it but that means more dependencies. Since I'm not the code owner we may want to wait for @jordansexton feedback.

**Comment by SilverSeva** [comment]
Hey, thats awesome @lorisleiva! Great Job

**Comment by lorisleiva** [comment]
That's a good shout, I'll get started with the core adapter first to provide a more digestible PR.

I see what you mean about the extra dependency but I don't think Vue has any official UI libraries so there would be a need for extra dependencies anyway. With Tailwind I can make sure to purge any unused classes to make the final minified CSS super tiny. Anyway, that's my case for Tailwind but I'm more than happy to integrate it with something else. 😅

**Comment by danmt** [comment]
I'm not familiar with Vue tbh, I don't know the UI alternatives. But I love TW and if it's already a dependency I'd use it for the angular support. The thing is that it's not up to me to decide.

**Comment by jordansexton** [comment]
> That's a good shout, I'll get started with the core adapter first to provide a more digestible PR.

Awesome! Yeah, I think having a core package for the state management expected by Vue (Vuex?) users is a good start and will help frame how we think about structuring and maintaining the UI components.

> Regarding TailwindCSS, I'm really a fan of it but that means more dependencies.

If there's a `core/vue` package and a `ui/vue-ui` package, it could include a CSS framework, but I might like to see something closer to the `ui/react-ui` package, which has few dependencies, the styles are easy to override, and it's extensible if you choose to fork it.

Tailwind is a pretty opinionated framework. I think whether we want to use Tailwind depends on how common/idiomatic it is for Vue apps to use Tailwind versus some other CSS/CSS-in-JS solution, and whether we need a framework at all for the small number of components we expect.

**Comment by devpake** [comment]
I ended up here for the exact reason of wanting a Vue version.  Glad to see this moving!

>  it could include a CSS framework, but I might like to see something closer to the ui/react-ui package, which has few dependencies, the styles are easy to override, and it's extensible if you choose to fork it.

I have my vote for this approach. Leaves the freedom for users to style on their own.  Ideally a default style can be scoped to just the component and class `props` (whether TW or otherwise) can be still be passed to override the default.  While I enjoy using TW, I like the freedom to change if needed.

**Comment by lorisleiva** [comment]
So I've made some progress by translating the app files to TypeScript but I'm having issues when compiling due to Vue 3 and the `--isolatedModules` flag even though the const enums mentioned below are not actually being used by what I am tree shaking.

```
../../../node_modules/@vue/runtime-core/dist/runtime-core.d.ts:1187:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

1187     [BooleanFlags.shouldCast]?: boolean;
          ~~~~~~~~~~~~

../../../node_modules/@vue/runtime-core/dist/runtime-core.d.ts:1188:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

1188     [BooleanFlags.shouldCastTrue]?: boolean;
          ~~~~~~~~~~~~

../../../node_modules/@vue/runtime-core/dist/runtime-core.d.ts:1722:10 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

1722 export { TrackOpTypes }
              ~~~~~~~~~~~~

../../../node_modules/@vue/runtime-core/dist/runtime-core.d.ts:1751:10 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

1751 export { TriggerOpTypes }
              ~~~~~~~~~~~~~~


Found 4 errors.
```

I can confirm that the error comes from this import line:

```js
import { ref, computed, Ref, watch, watchEffect } from 'vue';
```

More precisely, the error comes from `@vue/runtime-core`.

```js
import { watch, watchEffect } from '@vue/runtime-core';
```

Since I can get the other values from `@vue/reactivity` without any issue.

```js
import { ref, computed, Ref } from '@vue/reactivity';
```

I've looked everywhere online and searched the Vue 3 issues and there's nothing that mentions this so my guess is I must be doing something wrong. I'm fairly new to TypeScript so I wouldn't be surprised.

Any help would be much appreciated. You can find [the repo I'm working on here](https://github.com/lorisleiva/wallet-adapter/blob/feature/add-vue-core/packages/core/vue/src/useWallet.ts). 🙏

**Comment by danmt** [comment]
Did you try overriding `isolatedModules` flag [here](https://github.com/lorisleiva/wallet-adapter/blob/feature/add-vue-core/packages/core/vue/tsconfig.json#L4)? I'm not sure how this would affect your code but here's the documentation about [isolatedModule flag](https://www.typescriptlang.org/tsconfig#isolatedModules)

**Comment by lorisleiva** [comment]
Thanks Daniel, setting this flag to false on the vue core package did the trick! 🙇‍♂️ Now I can continue on my journey. 😊

**Comment by lorisleiva** [comment]
On top of [that first core PR](https://github.com/solana-labs/wallet-adapter/pull/107), I've managed to recreate the UI for Vue using the exact same stylesheet as the React UI for consistency (so not using TailwindCSS in the end).

So far this is not typed or extracted to a library but simply lives inside a dummy app I'm playing with. When/if that first PR is merged I can extract that on a `ui/vue-ui` PR that will make use of `core/vue`.

In the meantime, if anyone wants to check the code of that dummy app, [you can find it here](https://github.com/lorisleiva/solana-vue3-counter/tree/main/app). Here's a quick demo below using the wallet-adapter UI for Vue.

https://user-images.githubusercontent.com/3642397/135502773-aea2dd5f-0899-4d20-b724-5a766891f398.mp4

**Comment by scorpnode** [comment]
Do you have a non typescript version? Cheers

**Comment by jordansexton** [comment]
Closing this issue for housekeeping since @lorisleiva's excellent PR (https://github.com/solana-labs/wallet-adapter/pull/107) will be merged soon. Please follow that PR for updates.
