### ISSUE TITLE
Next 13: missing dependencies

### ISSUE THREAD

**Issue by Manuelandro** [solana-labs/wallet-adapter#694]
adding the module to Next 13 keeps telling me about missing dependencies

<img width="1075" alt="Schermata 2022-12-28 alle 13 22 18" src="https://user-images.githubusercontent.com/3776546/209811809-73080334-eb00-49b8-a198-0d01b42facde.png">

Notes that this happens at build time and that i've dynamically imported all the components with the ssr flag set to false

**Comment by schellenbergk** [comment]
I wasn't able to get it working in 13 either... If you do let me know.

**Comment by steveluscher** [comment]
Did you add the Torus wallet adapter explicitly, or did you add it implicitly by importing `@solana/wallet-adapter-wallets`?

**Comment by jachughes** [comment]
I'm also having a lot of issues when using NextJS 13 and the new App Folder.

I'm able to get it working on a new project (npx create-next-app@latest --experimental-app) after manually installing 'better-sqlite3' as it says It's missing otherwise. It's also throwing the following errors:

![Wallet Adapter Errors](https://user-images.githubusercontent.com/104396396/213569190-4dfe9902-b2dd-4f21-b00b-502b884c9332.png)

**Comment by crypt0miester** [comment]
hi, got next 13 working but without `@solana/wallet-adapter-wallets`

you will have to add individual wallets i.e. `@solana/wallet-adapter-phantom` to make next 13 work.

**Comment by Woody4618** [comment]
I am having the same Issue: [crypt0miester](https://github.com/crypt0miester) solution fixed it for me as well. As soon as I add 
```
import {
  PhantomWalletAdapter
} from "@solana/wallet-adapter-wallets";
```
it breaks.

**Comment by steveluscher** [comment]
Hey folks. I just created a brand new Next 13 application using `pnpm create next-app` and wasn't able to reproduce this. 

```ts
// This generated no errors for me.
import { PhantomWalletAdapter } from "@solana/wallet-adapter-wallets";
```

I'm happy to debug this, if one of you can put up an example repo that reproduces the problem!

**Comment by Woody4618** [comment]
Hey, thank you! Here for example: https://github.com/Woody4618/workshops_fork/tree/main/workshops/tug-of-war

**Comment by crypt0miester** [comment]
btw I think the issue is in one of those big wallet repos. torus wallet? 

I'll double check this. but it is one of these.

**Comment by steveluscher** [comment]
Related: https://github.com/WalletConnect/walletconnect-utils/pull/31

**Comment by steveluscher** [comment]
So listen, the problem here is:

1. When Next server side renders the app, all of these wallets' Node.js bindings kick in. None of which are actually installed.
2. Server rendering fails.
3. When the code loads in the browser, the browser bundle is chosen and the Node.js binding become irrelevant.

Notwithstanding that this is a whole entire mess, before version 1.0.2 of `@walletconnect/keyvaluestorage` that exception would bubble up to the _client_ as well. This has been fixed.

Two ‘fixes’ are necessary here:

1. It makes no sense to server render the wallet adapter parts of your app. Don't. The server has no access to your wallet in the browser. Hide everything that has to do with wallet connection behind a Next.js `dynamic` import with `{ssr: false}`. See example below.
2. I've asked for an upgrade of `@walletconnect/keyvaluestorage` [here](https://github.com/jnwng/walletconnect-solana/pull/8) so that I can include it in this package.

https://github.com/solana-labs/wallet-adapter/blob/de22df4d08e5af3d4d56aec7bd8823dce13a9aea/packages/starter/nextjs-starter/src/pages/index.tsx#L8-L15

**Comment by steveluscher** [comment]
@jnwng @jordansexton it's time to kick these UI packages out of `wallet-adapter`.
