### ISSUE TITLE
Type error: Cannot invoke an object which is possibly 'undefined'.

### ISSUE THREAD

**Issue by tooka-sol** [solana-labs/wallet-adapter#702]
```
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
const { connected, publicKey, signTransaction, signMessage } = useWallet();


const r = await signMessage(new TextEncoder().encode("test"));
               //^^ error here

```

**Comment by steveluscher** [comment]
Thanks for the report! Can you retrieve the stack trace and add it to your report? Also helpful will be the version of `@solana/wallet-adapter-react` and `@solana/web3.js` in your project, as well as whether this is a browser or React Native.

**Comment by jordansexton** [comment]
This is because `signMessage` can be `undefined`. The method is not guaranteed to be supported by a wallet. You need to check for it before trying to call it, e.g. https://github.com/solana-labs/wallet-adapter/blob/ec9451cbcf29cae978aff4552bdbcdfd9afddb1d/packages/starter/example/src/components/SignMessage.tsx#L16
