### ISSUE TITLE
Can't inspect sendTransaction method when using Phantom adapter

### ISSUE THREAD

**Issue by thanhvk** [solana-labs/wallet-adapter#705]
Hi,

Recently, I noticed when using the Phantom adapter with method `sendTransaction`
we can't inspect request `sendTransaction` in browser like Chrome

but I can inspect sendTransaction when using Solflare adapter.
![sendTransaction](https://user-images.githubusercontent.com/11411161/213076101-e89f981b-ba42-40fd-81b6-9905f54a4045.png)

Can you explain to me why?

**Comment by jordansexton** [comment]
This is really a question for Phantom or Solflare. I can tell you it doesn't have anything to do with the Wallet Adapter, specifically.

My guess is that it's because `sendTransaction` in Phantom actually signs and sends the tx through Phantom, which occurs in the background, inside the extension and not the window object. In Solflare, perhaps it's signing in the wallet but sending using the loaded Solflare SDK, inside the window, so you see it in the Network panel.

Please direct any follow up questions to those teams though :)
