### ISSUE TITLE
Cannot change wallet from Slope to other wallet extension

### ISSUE THREAD

**Issue by Somnus007** [solana-labs/wallet-adapter#709]
**Describe the bug**
1. Connect wallet in Slope extension
2. Click `WalletMultiButton` to show dropdown actions, then click `Change wallet`, you can see the wallet selection popup
3. Select `Phantom` wallet, the wallet selection modal will be closed automatically, but the `Phantom wallet` is not connected.

**To Reproduce**
1. Connect wallet in Slope extension
2. Click `WalletMultiButton` to show dropdown actions, then click `Change wallet`, you can see the wallet selection popup
3. Select `Phantom` wallet, the wallet selection modal will be closed automatically, but the `Phantom wallet` is not connected.

**Expected behavior**
A `Phantom wallet` is connected.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Browser: chrome
 - Version: 109.0.5414.87

**Comment by jordansexton** [comment]
Since the Slope adapter is something in your app, and the app code isn't linked here, the steps provided aren't sufficient to reproduce the issue. I would also recommend removing the Slope adapter from your application. Since the exploit of the Slope wallet, it is no longer maintained, and should not be used for any reason.
