### ISSUE TITLE
Expose `Cluster` that the currently connected wallet is attached to.

### ISSUE THREAD

**Issue by jessupjn** [solana-labs/wallet-adapter#717]
When we build a transaction expecting the wallet to be connected to `devnet` but the wallet is connected to `mainnet-beta` (or vice versa) - the simulation prior to submitting the txn fails and introduces an added layer of friction to the user signing the transaction.

When a wallet is connected - it would be very helpful to either:
1) Expose a `wallet.cluster` or `wallet.networkId` parameter so that the UI can show an error if not in sync with the expected network
2) Allow the user to select which network ID they desire to sign a transaction on.

If this isn't a possibility - is there another recommended course of action?

**Comment by jordansexton** [comment]
Wallets generally don't expose which cluster they are configured to use. [This StackExchange answer](https://solana.stackexchange.com/questions/141/what-method-should-a-dapp-use-to-detect-a-change-in-wallet-network-for-any-walle/309#309) provides more context.

As of now, Backpack is the only wallet I'm aware of that exposes the connection, via `window.backpack.connection`, and you still can't get the cluster from this (because it's not part of the web3.js `Connection` class) except with fuzzy detection against the connection's `rpcEndpoint`. Here's a [stale PR](https://github.com/solana-labs/solana/pull/28435), but for this to work, it would still require wallets to expose this.

I'm going to close this issue because it's not something Wallet Adapter can do without wallet support. For what it's worth, the Wallet Standard _does_ expose this via the [`Wallet::chains`](https://github.com/wallet-standard/wallet-standard/blob/2e5c9bb5346fc9a485c8d603fc276d145c68af28/packages/core/base/src/wallet.ts#L55-L68) property. But this isn't very useful without wallets fully implementing the Standard as designed. Some have implemented it, but still don't expose this the way you want.

**Comment by jordansexton** [comment]
I just want to say, I know this UX sucks. I wish major wallets would fix it, but they haven't, so there isn't much we can do here before they do.
