### ISSUE TITLE
 signMessage is not a function 

### ISSUE THREAD

**Issue by ymc182** [solana-labs/wallet-adapter#72]
![image](https://user-images.githubusercontent.com/12613450/133249661-581623ff-1c21-435a-a76c-207a9f0cfcf0.png)
![image](https://user-images.githubusercontent.com/12613450/133249774-1ab87300-9deb-4908-b697-c354c67faa7f.png)

I am trying to sign a message and it worked once I am not sure why but most of the time it return error saying sendMessage is not a function

**Comment by jordansexton** [comment]
That's because `signMessage` is an optional interface method -- Phantom is the first wallet to support it. You need to check if the method is defined before you use it, e.g. `if (signMessage) { ... }`

Please see the example package for how this is done, and try viewing the UI examples at https://solana-labs.github.io/wallet-adapter/example/

You'll see that the button to sign a message only appears when Phantom is selected and is only enabled when it's connected.

If you know you're only going to use wallets that support this optional API, you can pass only Phantom for now to your `wallets` array, and then you can use the method as long as it's connected.
