### ISSUE TITLE
Phantom wallet doesn't show up in Firefox / Ubuntu using standard wallet adapter 

### ISSUE THREAD

**Issue by robbestad** [solana-labs/wallet-adapter#722]
**Describe the bug**
Phantom wallet doesn't appear in the list of wallets you can select if you don't specify this in the list of adapters. This is specific to Firefox since it shows up in Brave.

**To Reproduce**
Default setup as shown in the docs https://github.com/solana-labs/wallet-adapter/blob/master/APP.md

**Expected behavior**
Expected Phantom wallet to show up as a wallet to connect to

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox 
 - Version 109.0.1

**Comment by daoplays** [comment]
I also am seeing this.  Updating all my packages to the latest versions and now the wallet won't load phantom on brave browser on mac, or firefox.

works fine with chrome on ubuntu and mac, as well as on android phone.

**Comment by jordansexton** [comment]
Could I ask you to test using this example page and let me know if it still happens?

https://solana-labs.github.io/wallet-adapter/example/

**Comment by bfriel** [comment]
@jordansexton I just tested both Firefox and Brave and there are no issues with the latest version of Phantom (`v23.2.1`)

I believe this issue is the result of using an older version of Phantom that does not contain support for Wallet Standard.

Phantom was inadvertently removed from the Firefox Add-on Store prior to our support for Wallet Standard. It was only re-instated this week, which might explain why @robbestad had issues last week.

Brave uses Chrome's extension store, so I suspect that @daoplays's Brave browser was using an older version of Phantom while their Chrome browser was using the latest

**Comment by robbestad** [comment]
That sounds like a likely explanation. Firefox's Phantom also seem to lag behind and is not as feature rich as Chrome's.

**Comment by steveluscher** [comment]
Feel free to reopen this if there's new information!
