### ISSUE TITLE
WalletDisconnectError on example page

### ISSUE THREAD

**Issue by david-dacruz** [solana-labs/wallet-adapter#742]
Hi I see an error on the example page and also in my implementation when disconnecting a wallet is there any known fixes for this?

Thanks ahead
<img width="745" alt="Screenshot 2023-02-25 at 11 15 17" src="https://user-images.githubusercontent.com/10786611/221353864-3e5eaa21-477e-46d1-b69f-0e67a2c74e36.png">

**Comment by jordansexton** [comment]
This is expected behavior. The wallet adapter throws an error for the dapp if the wallet is disconnected for some reason. When the dapp disconnects the wallet, the listener for this error is removed so that this doesn't occur. You should be aware of this error and catch it in your dapp so that you know when the wallet becomes disconnected, and your UI can respond to this.

**Comment by davodesign84** [comment]
@jordansexton I know you mention that it is expected behaviour but the majority of other wallets do no behave like so. (e.g. Solflare)

**Comment by jordansexton** [comment]
More context on this here: https://github.com/solana-labs/wallet-standard/pull/14#issuecomment-1468727949

If the adapter triggers the disconnection, this is an _endogenous_ disconnection. We expect it, so there's no error, just a disconnect event.

If the wallet triggers the disconnection, this is an _exogenous_ disconnection. We don't expect it, and usually can't tell why it happened, so there's an error, and a disconnect event.
