### ISSUE TITLE
Sollet rpc url is preselected as solana-api.projectserum.com even though I set custom programatically

### ISSUE THREAD

**Issue by nukec** [solana-labs/wallet-adapter#77]
If I set custom RPC and WSS in connection provider, shouldn't that reflect over all wallets?
Result when I try to use sollet:
![image](https://user-images.githubusercontent.com/3589518/133432838-39e76765-511f-4ac2-abdf-32fd56aa2f32.png)

Code where I set my own custom rpc in ConnectionProvider:
```
function EntryPoint() {
  let walletAdapterNetwork: WalletAdapterNetwork = WalletAdapterNetwork.Mainnet;
  const network = useRecoilValue(atomNetwork);
  const clusterUrl = useRecoilValue(atomClusterApiUrl);
  const clusterWssUrl = useRecoilValue(atomClusterWssApiUrl);

  if (network === NetworkEnum.devnet) {
    walletAdapterNetwork = WalletAdapterNetwork.Devnet;
  } else if (network === NetworkEnum.testnet) {
    walletAdapterNetwork = WalletAdapterNetwork.Testnet;
  }

  const wallets = useMemo(
    () => [
      getBitpieWallet(),
      getBloctoWallet({ network: walletAdapterNetwork }),
      getCoin98Wallet(),
      getLedgerWallet(),
      getMathWallet(),
      getPhantomWallet(),
      getSafePalWallet(),
      getSlopeWallet(),
      getSolletWallet({ network: walletAdapterNetwork }),
      getSolletExtensionWallet({ network: walletAdapterNetwork }),
      getSolflareWallet(),
      getSolflareWebWallet(),
      getSolongWallet(),
      getTorusWallet({
        options: {
          clientId:
            "xxx",
        },
      }),
    ],
    [walletAdapterNetwork]
  );

  const config: ConnectionConfig = {
    commitment: SolanaCommitmentEnum.processed,
    wsEndpoint: clusterWssUrl,
  };

  const { enqueueSnackbar } = useSnackbar();

  const onError = useCallback(
    (error: WalletError) => {
      enqueueSnackbar(
        error.message ? `${error.name}: ${error.message}` : error.name,
        { variant: "error" }
      );
      console.error(error);
    },
    [enqueueSnackbar]
  );

  return (
    <div>
      <ConnectionProvider endpoint={clusterUrl} config={config}>
        <WalletProvider wallets={wallets} onError={onError} autoConnect={false}>
          <Game />
          <Logo />
          <WalletConnect />
          <WalletInfo />
          <ReactUIWalletModalProvider>
            <div>
              <ReactUIWalletMultiButton />
            </div>
          </ReactUIWalletModalProvider>
        </WalletProvider>
      </ConnectionProvider>
    </div>
  );
}

export default EntryPoint;
```

**Comment by jordansexton** [comment]
If I understand the question, I think the answer is no. Wallets may provide mechanisms for managing their own connections (e.g. to check lamport/token balances, perform swaps, etc.), and these are typically not exposed to dApps to manage. The dApp can't really do anything to keep these values in sync unless the wallet lets it.

In the case of Sollet, we only provide a network arg because it's expected by the wallet. However, the transactions the dApp sends are sent over the Connection object, so the setting in Sollet has no bearing on which cluster RPC endpoint will receive the transaction.

In the case of Blocto, this one is a bit tricky because Blocto uses a program to sign transactions on behalf of users. This means that it doesn't use the Connection object to broadcast the transaction, but it does use the Connection object's configuration for it's own internal RPC call. The dApp then uses the Connection object to confirm the transaction.

**Comment by jordansexton** [comment]
https://github.com/solana-labs/wallet-adapter/issues/46 will help when implemented, but respecting the connection settings of a dapp is really up to wallets to implement.

I'm closing this issue as I don't believe this is something in the scope of the library (we connect to wallets, we don't control them). Please reopen if there's a better argument.
