### ISSUE TITLE
wallet.disconnecting is not updated in useEffect hook on mobile chrome browser

### ISSUE THREAD

**Issue by newcometlab** [solana-labs/wallet-adapter#772]
I added some codes to see if wallet.disconnecting is updated on mobile chrome.
https://github.com/newcometlab/dapp-scaffold/blob/mobile-useeffect-test/src/views/home/index.tsx#L31-L33

And I deployed dapp-scaffold on vercel and opened a tab.
https://dapp-scaffold-mobile-useeffect-test.vercel.app/

I could see there is no update of wallet.disconnecting when I connect and disconnect phantom mobile app.

I had seen same issue with wallet.publicKey as well.

There was no issue in desktop browser.

I tested on this mobile device and browser.
 - Android v9
 - Chrome 112.0.5615.101

**Comment by mcintyre94** [comment]
Thanks for raising this, it looks like an issue with mobile wallet adapter.

I can repro using your example with multiple wallets in Android/Chrome

Seems to work correctly in desktop/Chrome, Android/Phantom in-app browser, iOS/Phantom in-app browser, iOS Safari/Glow extension. So I think this is an MWA issue. 

I'll do some digging and see if I can figure out what's going on!

**Comment by newcometlab** [comment]
@mcintyre94  You are right. `useEffect `updating on `wallet.publicKey` works correctly. Please ignore that comment.

**Comment by mcintyre94** [comment]
@newcometlab I've done some digging and this is basically down to react batching/rendering behaviour. We have multiple updates to the same piece of state (in this case `disconnecting`) and react can batch them, so you (and your `useEffect` hooks) might never see the `disconnecting(true)` state if a `disconnecting(false)` occurs right after it.

Can you explain exactly what you're trying to achieve so that I can try to give you a pointer to a different way to do it? Or if you do have a use case that we can't currently support then we can try to figure out the best way to support it.

**Comment by newcometlab** [comment]
@mcintyre94 Let me explain what I am trying to do.
- I have more than 2 pages. e.g. '/' and '/home'.
- If user clicks walletConnectButton at '/', then the user will be redirected to '/home'. I use WalletMultiButton in this page.
- If user clicks walletDisconnectButton at '/home', then the user will be redirected to '/'. I use custom button and call wallet.disconnect()

**Comment by jordansexton** [comment]
> * If user clicks walletDisconnectButton at '/home', then the user will be redirected to '/'. I use custom button and call wallet.disconnect()

I would probably not rely on the `disconnecting` state for this. If the disconnection occurs before the state updates, you won't get an intermediate `disconnecting` state (it happens too fast). In your custom button, I would call `wallet.disconnect()`, and then immediately (synchronously) redirect the user. You could also `await wallet.disconnect()` and then redirect after if you prefer, but I don't see a clear advantage.

**Comment by newcometlab** [comment]
@jordansexton I edited my comments above.

**Comment by newcometlab** [comment]
@jordansexton @mcintyre94 Is this issue solved?

**Comment by mcintyre94** [comment]
The resolution is to use something like what Jordan suggested above. You can't rely on the `disconnecting` state because it happens too fast, as explained above. I'm going to close this issue for now because I've investigated why using `disconnecting` is unreliable and we've decided we're not going to make changes related to that. Changing this would add unnecessary renders for all users of the library, and isn't the right place to hook this logic into anyway.

**Comment by newcometlab** [comment]
@mcintyre94 Is there any way to implement my needs? Can you give me any hint?

**Comment by mcintyre94** [comment]
If you don't want to use the solution Jordan gave then please open a question on the [stackexchange](https://solana.stackexchange.com) because this is a question of technical support, and not an issue with wallet-adapter.
