### ISSUE TITLE
Unexpected behavior when wallet.signMessage in useEffect - Mobile Chrome

### ISSUE THREAD

**Issue by newcometlab** [solana-labs/wallet-adapter#794]
I added some code info solana dapp-scaffold.
https://github.com/newcometlab/dapp-scaffold/blob/mobile-signmessage-test/src/views/home/index.tsx#L32-L48
https://dapp-scaffold-mobile-signmessage-test.vercel.app/

On mobile, I connected walllet, then I couldn't approve signMessage.
![wallet-test](https://github.com/solana-labs/wallet-adapter/assets/35681177/3f08beb0-a1b8-43ab-9810-8697a9ae31e8)

There was no issue in desktop browser.

- Android v9
- Chrome 112.0.5615.101v

**Comment by newcometlab** [comment]
Have anybody seen a similar issue to this?

**Comment by jordansexton** [comment]
Hmm, I'll flag this for someone on the Solana Mobile team. It looks like it's more likely to be something related to https://github.com/solana-mobile/mobile-wallet-adapter

**Comment by Michaelsulistio** [comment]
@newcometlab Hi! I'm from the Solana Mobile team and this is behavior is unfortunately due to a [known limitation](https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/156) with Android Chrome. By design, Android Chrome blocks all navigation that does **not** begin from a user gesture (i.e. pressing a button). 

In your case, `signMessage` tries to navigate to a wallet app, but it begins from a `useEffect` which is not a user gesture. This gets blocked by chrome, and you're instead sent to a fallback URL for wallet selection (because MWA thinks you have no available wallets).

Couple of questions for you:
- Whats the use-case you're trying to achieve for this `useEffect` -> `signMessage` flow? 
- Have you considered creating a native mobile app? On a mobile app, you won't run into this limitation.

**Comment by newcometlab** [comment]
@Michaelsulistio Thank you for dealing my issue!
- I want to create an access token by signMessage when users connect wallet.
- I am only considering web app.

**Comment by Michaelsulistio** [comment]
@newcometlab Gotcha. My recommendation is to detect when the user is an Android user on Chrome, then show them an alternate UI flow where they have to press some button to create an access token.

This current solution is not ideal, but in the future, we're exploring longer term solution where we can combine "connect + signMessage" from the first connect (a `signIn` API). @jordansexton has more info on this.
