### ISSUE TITLE
Sollet is not raising disconnect event on closing Sollet.io window

### ISSUE THREAD

**Issue by donkeizluv** [solana-labs/wallet-adapter#8]
**Reproduce:**

1. connect using Sollet adapter
2. close the Sollet child window

**Expected:**

- disconnect callback is invoked

**Actual:**

- disconnect callback is not invoked

Serum Sollet adapter is handling this using window beforeunload event

**Comment by jordansexton** [comment]
Thanks for the report! I'll check this out today.

**Comment by jordansexton** [comment]
This is handled now by https://github.com/solana-labs/wallet-adapter/blob/45013f04ea3be6a877e899f16c33d23884d147ec/packages/sollet/src/adapter.ts#L94 https://github.com/solana-labs/wallet-adapter/blob/45013f04ea3be6a877e899f16c33d23884d147ec/packages/sollet/src/adapter.ts#L156-L166

The same fix was made to the Ledger adapter. Thanks again!

**Comment by Sotatek-CongNguyen** [comment]
I met two issues: 
1. When I select Sollet wallet, it will open a new window instead of a new tab. Expect: open new tab
2. When I close the Sollet window, the connection status will be "disconnect". Then, I click connect button, It will open a new tab to sollet.io, I connect to my wallet but the connection status still is "disconnect"

**Comment by jordansexton** [comment]
@Sotatek-CongNguyen I'm just seeing this. In the future, if you create a new issue rather than comment on a closed issue, it will have better visibility.

>     1. When I select Sollet wallet, it will open a new window instead of a new tab. Expect: open new tab

To my knowledge, JavaScript cannot control or detect whether a popup opens in a new window or tab. That's a browser setting.

>     2. When I close the Sollet window, the connection status will be "disconnect". Then, I click connect button, It will open a new tab to sollet.io, I connect to my wallet but the connection status still is "disconnect"

Can you provide more context about the browser and device you're using that experiences this behavior?
