### ISSUE TITLE
Create NextJS 14 version

### ISSUE THREAD

**Issue by metasal1** [solana-labs/wallet-adapter#868]
**Describe the solution you'd like**
Update the Nextjs example to v14 using the App router

**Comment by ZYJLiu** [comment]
Here is a [minimal example](https://github.com/ZYJLiu/nextui-nextjs) using nextjs v14 App router to invoke a basic counter program

**Comment by Sagargajare** [comment]
Adding Nextjs 14 example with #869

**Comment by Manice18** [comment]
Is this issue still open to work or it is merged already? @metasal1

**Comment by DuttaArghya** [comment]
Updating NextJS-Starter to v14 with #870

**Comment by Sagargajare** [comment]
Adding Nextjs 14 example with #871 

(closed previous one)

**Comment by mcintyre94** [comment]
I don't think this is the right repo for a Next 14 example, so I'm going to close this. I can see this issue is linked from the gib.work bounty and I want to avoid anyone else being disappointed by us not merging their related PRs. The examples here have never been usable as-is, because they rely on `workspace` dependencies. This makes them useful for developing and testing `wallet-adapter`, and we don't want to lose that.

The best place to contribute this would be https://github.com/solana-developers/create-solana-dapp. This is intended to be used by developers as a quickstart for creating new dapps, so it serves exactly the purpose you're looking for here. It'll definitely help many more developers there. 

There's already an option to create a Next app there, which uses Next 13 with the `app/` directory. I'd suggest opening an issue in that repo to find out whether it'd be better to bump it to Next 14, or create a separate option between Next 13 and Next 14 if there are significant changes.
