### ISSUE TITLE
Can't resolve '@solana/wallet-adapter-base' in starter/example

### ISSUE THREAD

**Issue by oboxodo** [solana-labs/wallet-adapter#91]
**Describe the bug**
Trying to start the https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/example project fails.

**To Reproduce**

```sh
cd packages/starter/example
yarn
yarn start
```

And I get:
```
Failed to compile.

./src/Demo.tsx
Module not found: Can't resolve '@solana/wallet-adapter-base' in '/Users/oboxodo/repos/study/wallet-adapter/packages/starter/example/src'
```

**Expected behavior**
The example app works.

**Screenshots**
![image](https://user-images.githubusercontent.com/8324/134075079-8838b8ae-0fd8-4ef0-b3c7-2a41e8f7a10e.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - Version 93

**Comment by jordansexton** [comment]
Please read and follow the instructions to build from source: https://github.com/solana-labs/wallet-adapter#build-from-source

It looks like you're missing the call to `yarn install` and `yarn build` from the root directory before trying to run the starter project.

**Comment by oboxodo** [comment]
You're damn right, @jordansexton. 😬  Thanks!

**Comment by piscespieces** [comment]
Hi @jordansexton , thanks for your response. It also fixed some of the errors that I was getting. Nonetheless I would love to get a more elaborated response on "why?". Why the build command after the dep installation from the root directory is needed instead of going to the starter directory and installing deps from there and then launch to local server?

This is a humble question because it would be great to have a reference on "why" for those who are just getting started like me. Thanks again for your help!

**Comment by jordansexton** [comment]
Sure -- the project is built using Lerna, which resolves the dependencies the various packages in it have with each other. Since the packages are all TypeScript files in `src` dirs, running `yarn build` from the base directory is necessary to compile all of them to JavaScript in `lib` dirs, which is what is referenced by the package.json of each package.

These `lib` dirs aren't checked into Github, so they aren't there when you clone the project. Because Lerna resolves the dependency graph, it will build them in the correct order. Then when you run `yarn dev` from a starter project, all the deps it references (and their recursive deps) actually exist (symlinked in `node_modules`).
