### ISSUE TITLE
wallet publicKey is null

### ISSUE THREAD

**Issue by earth04190419** [solana-labs/wallet-adapter#92]
I connected to phantom wallet.

And then I try to get wallet by below code

`const wallet = useWallet();`

but wallet.publicKey is null.

I am not sure if this is a bug or I use this in a wrong way.

**Comment by jordansexton** [comment]
This is almost always because you don't have the React context set up properly: https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#-is-not-a-function---is-undefined--uncaught-typeerror-cannot-destructure-property--uncaught-in-promise-walletnotconnectederror

Please follow the setup code here: https://github.com/solana-labs/wallet-adapter#setup

**Comment by earth04190419** [comment]
Thank you. @jordansexton . Let me try.
